// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/aesthetic-procedures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aesthetic-procedures">> = Specific
  const handler = {} as typeof import("../../src/app/aesthetic-procedures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/career/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/career">> = Specific
  const handler = {} as typeof import("../../src/app/career/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/certifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certifications">> = Specific
  const handler = {} as typeof import("../../src/app/certifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/healthcare-providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/healthcare-providers">> = Specific
  const handler = {} as typeof import("../../src/app/healthcare-providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/investors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investors">> = Specific
  const handler = {} as typeof import("../../src/app/investors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leadership/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leadership">> = Specific
  const handler = {} as typeof import("../../src/app/leadership/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/medical-device-companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/medical-device-companies">> = Specific
  const handler = {} as typeof import("../../src/app/medical-device-companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../src/app/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/our-companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/our-companies">> = Specific
  const handler = {} as typeof import("../../src/app/our-companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/partnerships/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partnerships">> = Specific
  const handler = {} as typeof import("../../src/app/partnerships/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quality">> = Specific
  const handler = {} as typeof import("../../src/app/quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/regulatory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/regulatory">> = Specific
  const handler = {} as typeof import("../../src/app/regulatory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/research-development/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research-development">> = Specific
  const handler = {} as typeof import("../../src/app/research-development/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/research-institutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research-institutions">> = Specific
  const handler = {} as typeof import("../../src/app/research-institutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/safety/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safety">> = Specific
  const handler = {} as typeof import("../../src/app/safety/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tissue-processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tissue-processing">> = Specific
  const handler = {} as typeof import("../../src/app/tissue-processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wound-care-applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wound-care-applications">> = Specific
  const handler = {} as typeof import("../../src/app/wound-care-applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
